jobs:
  include:
    - stage: test
      language: python
      python:
        - "3.6"
      env:
        - DJANGO_SETTINGS_MODULE='pur_beurre_web.settings.travis' MOZ_HEADLESS=1
      addons:
        postgresql: "9.4"
        firefox: latest
      services:
        - postgresql
      before_install:
        - wget https://github.com/mozilla/geckodriver/releases/download/v0.22.0/geckodriver-v0.22.0-linux64.tar.gz
        - mkdir geckodriver
        - tar -xzf geckodriver-v0.22.0-linux64.tar.gz -C geckodriver
        - export PATH=$PATH:$PWD/geckodriver
        - geckodriver --version
        - export MOZ_HEADLESS=1
      install:
        - pip install pipenv
        - pipenv lock
        - pipenv install
      before_script:
        - psql -c 'create database travis_ci_test;' -U postgres
      script:
        - python manage.py migrate
        - python manage.py test
    - stage: deploy
      if: branch = master
      language: minimal
      before_script:
        - openssl aes-256-cbc -K $encrypted_cf020907aa56_key -iv $encrypted_cf020907aa56_iv -in deploy/deploy_key.enc -out deploy/deploy_key -d
        - chmod +x deploy/deploy.sh
      script: deploy/deploy.sh