language: python
python:
  - "3.7"
env:
  - DJANGO_SETTINGS_MODULE='pur_beurre_web.settings.test'
install:
  - pip install pipenv
  - pipenv install
script:
  - python manage.py migrate
  - python manage.py test