language: python
python:
  - "3.7-dev"
services:
  - postgresql
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
env:
  - DJANGO_SETTINGS_MODULE='pur_beurre_web.settings.test'
install:
  - pip install pipenv
  - pipenv install
script:
  - python manage.py migrate
  - python manage.py test