version: '3'
services:
  purbeurre:
    restart: always
    build: .
    image: purbeurre:latest
    env_file:
      - ./.env
    volumes:
      - /var/www/purbeurre/static:/var/www/static

    networks:
      purbeurre-ntk:
        ipv4_address: 172.30.0.2

    depends_on:
      - db

  purbeurre_update:
    build: .
    image: purbeurre_update:latest
    env_file:
      - ./.env
    volumes:
      - update_history:$LAST_PAGE_HISTORY_PATH
    networks:
      purbeurre-ntk:
        ipv4_address: 172.30.0.5
    command: python manage.py api_to_db --grumpy_mode
    depends_on:
      - db
  db:
    restart: always
    image: postgres:latest
    env_file:
      - ./.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      purbeurre-ntk:
        ipv4_address: 172.30.0.3

networks:
  purbeurre-ntk:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/24


volumes:
  pgdata:
  update_history:
