# Generated by Django 2.1 on 2018-08-15 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitute_finder', '0003_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='category',
            name='url',
            field=models.URLField(max_length=1000, verbose_name='url'),
        ),
    ]
