# Generated by Django 2.1 on 2018-08-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitute_finder', '0005_auto_20180816_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_front_small_url',
            field=models.URLField(default='https://fake_image/fake.jpg', max_length=2000, verbose_name='url de la miniature'),
            preserve_default=False,
        ),
    ]
