# Generated by Django 2.1 on 2018-09-04 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitute_finder', '0006_product_image_front_small_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(default=1, max_length=2000, verbose_name="url de l'image"),
            preserve_default=False,
        ),
    ]
