# Generated by Django 2.1 on 2018-09-05 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitute_finder', '0007_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='energy_100g',
            field=models.FloatField(blank=True, null=True, verbose_name='Valeur énergétique pour 100g'),
        ),
    ]
