# Generated by Django 2.1 on 2018-09-05 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitute_finder', '0008_product_energy_100g'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='carbohydrates_100g',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Valeur énergétique pour 100g'),
        ),
        migrations.AddField(
            model_name='product',
            name='carbohydrates_unit',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Valeur énergétique pour 100g'),
        ),
        migrations.AddField(
            model_name='product',
            name='energy_unit',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Valeur énergétique pour 100g'),
        ),
        migrations.AddField(
            model_name='product',
            name='fat_100g',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Valeur énergétique pour 100g'),
        ),
        migrations.AddField(
            model_name='product',
            name='fat_unit',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Valeur énergétique pour 100g'),
        ),
        migrations.AddField(
            model_name='product',
            name='fiber_100g',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Valeur énergétique pour 100g'),
        ),
        migrations.AddField(
            model_name='product',
            name='fiber_unit',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Valeur énergétique pour 100g'),
        ),
        migrations.AddField(
            model_name='product',
            name='proteins_100g',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Valeur énergétique pour 100g'),
        ),
        migrations.AddField(
            model_name='product',
            name='proteins_unit',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Valeur énergétique pour 100g'),
        ),
        migrations.AddField(
            model_name='product',
            name='salt_100g',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Valeur énergétique pour 100g'),
        ),
        migrations.AddField(
            model_name='product',
            name='salt_unit',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Valeur énergétique pour 100g'),
        ),
        migrations.AddField(
            model_name='product',
            name='sodium_100g',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Valeur énergétique pour 100g'),
        ),
        migrations.AddField(
            model_name='product',
            name='sugars_100g',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Sucre pour 100g'),
        ),
        migrations.AddField(
            model_name='product',
            name='sugars_unit',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Valeur énergétique pour 100g'),
        ),
        migrations.AlterField(
            model_name='product',
            name='energy_100g',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Valeur énergétique pour 100g'),
        ),
    ]
