# Generated by Django 2.1 on 2018-09-06 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('substitute_finder', '0009_auto_20180906_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='saturated_fat_100g',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Acides gras saturés pour 100g'),
        ),
        migrations.AddField(
            model_name='product',
            name='saturated_fat_unit',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Unité acides gras saturés'),
        ),
        migrations.AlterField(
            model_name='product',
            name='carbohydrates_100g',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Glucides pour 100g'),
        ),
        migrations.AlterField(
            model_name='product',
            name='carbohydrates_unit',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Unité glucides'),
        ),
        migrations.AlterField(
            model_name='product',
            name='energy_unit',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Unité valeur énergétique'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fat_100g',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Matières grasses pour 100g'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fat_unit',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Unité matières grasses'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fiber_100g',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Fibres pour 100g'),
        ),
        migrations.AlterField(
            model_name='product',
            name='fiber_unit',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Unité fibres alimentaires'),
        ),
        migrations.AlterField(
            model_name='product',
            name='proteins_100g',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Protéines pour 100g'),
        ),
        migrations.AlterField(
            model_name='product',
            name='proteins_unit',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Unité protéines'),
        ),
        migrations.AlterField(
            model_name='product',
            name='salt_100g',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Sel pour 100g'),
        ),
        migrations.AlterField(
            model_name='product',
            name='salt_unit',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Unité sel'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sodium_100g',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Sodium pour 100g'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sugars_unit',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Unité sucre'),
        ),
    ]
