# Generated by Django 2.1.4 on 2019-01-03 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('substitute_finder', '0011_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['product', '-created'], 'permissions': (('can_change_all_commments', 'Can modify all the comments'), ('can_delete_all_comments', 'Can delete all the comments')), 'verbose_name': 'commentaire', 'verbose_name_plural': 'commentaires'},
        ),
    ]
